# -*- coding: utf-8 -*-
"""Most Subscribed YouTube Channel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CUxUJS6dpdpTiPVA6OhczR-W6mt9GUXZ

# **IMPORT LIBRARY**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

"""# **DATA**"""

data = pd.read_csv("Most Subscribed YouTube Channels_exported.csv")
print(data.shape)

"""# **EXPLORATORY DATA ANALYSIS**

## Data Information
"""

data.info()

data.head()

"""## Identify Missing Values"""

print(data.isnull().sum())

"""# **DATA PREPROCESSING**

## Data Cleaning
"""

# Cleaning data on "Primary language" and "Country" coloumn
# Removing numbers in square brackets and extra spaces
data['Primary language'] = data['Primary language'].apply(lambda x: re.sub(r'\[\d+\]', '', x).strip())
def clean_country(country):
    country = re.sub(r'\s*\(.*\)', '', country)
    country = re.sub(r'[^\w\s-]', '', country)
    country = country.strip()
    country = country.replace('\xa0', ' ')
    country = country.split('-')[0].strip()
    return country

data['Country'] = data['Country'].apply(clean_country)

print(data['Primary language'].unique())
print(data['Country'].unique())

"""# **SAVE DATA**"""

# Save data format Excel
data.to_excel('Most Subscribed YouTube Channel.xlsx', index=False)

# Save data format CSV
data.to_csv('Most Subscribed YouTube Channel.csv', index=False)

data.head()