# -*- coding: utf-8 -*-
"""Most Subscribed YouTube Channel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CUxUJS6dpdpTiPVA6OhczR-W6mt9GUXZ

# **IMPORT LIBRARY**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

"""# **DATA**"""

# Membaca data
data = pd.read_csv("Most Subscribed YouTube Channels_exported.csv")
# Menampilkan jumlah baris dan kolom
print(data.shape)

"""# **EXPLORATORY DATA ANALYSIS**"""

# Menampilkan informasi data
data.info()

# Menampilkan data awal
data.head()

# Kolom Primary Language, Category, dan Country
kolom_kategorik = ['Primary language', 'Category', 'Country']
# Daftar warna plot
colors = ['skyblue', 'salmon', 'lightgreen', 'orange', 'lightcoral', 'cornflowerblue']
plt.figure(figsize=(12, 6))
# Looping for untuk mendapatkan indeks fitur dengan nilai kolomnya
for i, column in enumerate(kolom_kategorik):
    plt.subplot(2, 3, i + 1)
    # Membuat diagram batang
    data[column].value_counts().plot(kind='bar', color=colors, fontsize = 10)
    plt.title(column, fontsize=15)
    plt.xlabel('')
    plt.ylabel('Count')
    plt.tight_layout()

# Kolom Primary Language, Category, dan Country
kolom = ['Primary language', 'Category', 'Country']
# Daftar warna plot
colors = ['skyblue', 'salmon', 'lightgreen', 'orange', 'lightcoral', 'cornflowerblue']

# Ukuran plot
plt.figure(figsize=(12, 6))

# Looping untuk menampilkan diagram
for i, column in enumerate(kolom):
    plt.subplot(2, 3, i + 1)
    data.groupby(column)['Subscribers (millions)'].sum().sort_values().plot(kind='bar', color=colors, fontsize = 10)
    plt.title(f'Subscribers by {column}', fontsize=15)
    plt.xlabel('')
    plt.ylabel('Total')
    plt.tight_layout()

plt.show()

# Kolom Name
kolom = ['Name']
colors = ['cornflowerblue']

plt.figure(figsize=(12, 6))
for i, column in enumerate(kolom):
    data.groupby(column)['Subscribers (millions)'].sum().sort_values().plot(kind='bar', color=colors, fontsize = 10)
    plt.title(f'Subscribers by {column}', fontsize=15)
    plt.xlabel('')
    plt.ylabel('Total')
    plt.tight_layout()

plt.show()

"""# **DATA PREPROCESSING**"""

# Memeriksa jumlah missing value di setiap kolom
missing_values = data.isnull().sum()
print(missing_values)

# Membersihkan data pada kolom "Primary language" dan "Country"
# Menghapus angka dalam tanda siku dan spasi tambahan
data['Primary language'] = data['Primary language'].apply(lambda x: re.sub(r'\[\d+\]', '', x).strip())
# Menghapus teks dalam tanda kurung
data['Country'] = data['Country'].apply(lambda x: re.sub(r'\s*\(.*\)', '', x))
# Menghapus karakter khusus selain huruf dan spasi
data['Country'] = data['Country'].apply(lambda x: re.sub(r'[^\w\s]', '', x))
# Menghapus spasi tambahan di awal dan akhir
data['Country'] = data['Country'].str.strip()

# Menampilkan data unik setelah membersihkan
print(data['Primary language'].unique())
print(data['Country'].unique())

# Menyimpan data yang sudah dibersihkan dalam format Excel
data.to_excel('Most Subscribed YouTube Channel.xlsx', index=False)

# Menyimpan data yang sudah dibersihkan dalam format CSV
data.to_csv('Most Subscribed YouTube Channel.csv', index=False)

data.head()