# -*- coding: utf-8 -*-
"""Most Subscribed YouTube Channel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CUxUJS6dpdpTiPVA6OhczR-W6mt9GUXZ

# **IMPORT LIBRARY**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

"""# **DATA**"""

data = pd.read_csv("Most Subscribed YouTube Channels_exported.csv")
print(data.shape)

"""# **EXPLORATORY DATA ANALYSIS**

## Data Information
"""

data.info()

data.head()

"""## Identify Missing Values"""

print(data.isnull().sum())

"""# **DATA PREPROCESSING**

## Data Cleaning
"""

# Menghapus angka dalam tanda siku dan spasi tambahan pada "Primary language"
data['Primary language'] = data['Primary language'].apply(lambda x: re.sub(r'\[\d+\]', '', x).strip())

# Fungsi untuk membersihkan kolom "Country"
def clean_country(country):
    # Menghapus teks dalam tanda kurung
    country = re.sub(r'\s*\(.*\)', '', country)
    # Menghapus karakter khusus selain huruf dan spasi
    country = re.sub(r'[^\w\s-]', '', country)
    # Menghapus spasi tambahan di sekitar tanda hubung dan menggantinya dengan spasi
    country = re.sub(r'\s*-\s*', ' ', country)
    # Menghapus spasi tambahan di awal dan akhir
    country = country.strip()

# Menerapkan fungsi pembersihan pada kolom "Country"
data['Country'] = data['Country'].apply(clean_country)

# Menampilkan data unik setelah membersihkan
print(data['Primary language'].unique())
print(data['Country'].unique())

# Cleaning data on "Primary language" dan "Country" coloumn
# Removing numbers in square brackets and extra spaces
data['Primary language'] = data['Primary language'].apply(lambda x: re.sub(r'\[\d+\]', '', x).strip())
def clean_country(country):
    country = re.sub(r'\s*\(.*\)', '', country)  # Menghapus teks dalam tanda kurung
    country = re.sub(r'[^\w\s-]', '', country)  # Menghapus karakter khusus selain huruf, spasi, dan tanda hubung
    country = country.strip()  # Menghapus spasi tambahan di awal dan akhir
    country = country.replace('\xa0', ' ')
    country = country.split('-')[0].strip()  # Ambil hanya negara pertama jika ada tanda hubung
    return country

# Bersihkan kolom "Country"
data['Country'] = data['Country'].apply(clean_country)

print(data['Primary language'].unique())
print(data['Country'].unique())

# Menyimpan data yang sudah dibersihkan dalam format Excel
data.to_excel('Most Subscribed YouTube Channel.xlsx', index=False)

# Menyimpan data yang sudah dibersihkan dalam format CSV
data.to_csv('Most Subscribed YouTube Channel.csv', index=False)

data.head(50)